//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWL_Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ivr_Themes
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string uuid { get; set; }
        public Nullable<int> vmid { get; set; }
        public Nullable<int> intid { get; set; }
    }
}
