---
title: "Plotly presentation"
author: "Alex Pilugin"
date: '25th of December, 2017'
output: ioslides_presentation
editor_options: 
  chunk_output_type: console
---
## Supplementary code

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = "")
```
```{r, message = FALSE, results = "hide", warning = FALSE}
Sys.setlocale("LC_TIME", "English")
library(knitr)
library(plotly)
library(ggplot2)
library(magrittr)
```
```{r}  
data(iris)
g1 <- ggplot(data = iris) +
    geom_point(aes(x = Sepal.Length, y = Petal.Length, 
                   color = Species)) +
    geom_smooth(aes(x = Sepal.Length, y = Petal.Length, 
                    color = Species))
g2 <- ggplot(data = iris) +
    geom_point(aes(x = Sepal.Width, y = Petal.Width, 
                   color = Species)) +
    geom_smooth(aes(x = Sepal.Width, y = Petal.Width, 
                    color = Species))
```  

## GGplot 1  
```{r, message = FALSE, warning = FALSE}  
g1
```  

## GGplot 2  
```{r, message = FALSE, warning = FALSE}  
g2
```  

## Plotly 1  
```{r, message = FALSE, warning = FALSE}  
(gg1 <- ggplotly(g1))
```  

## Plotly 2  
```{r, message = FALSE, warning = FALSE}  
(gg2 <- ggplotly(g2))
```  